feat: add the ability to run tests manually
Drill4J/vee-table pull request #1
Opened 2022-01-14 12:18 UTC by IliaSolovev

2022-01-17 09:46 UTC, RomanDavlyatshin requested changes
The main request: move _all_ calls to e2e repository to the separate module, with clearly defined interface. `export { doThis, doThat, doSomethingElse, getSomeData}`
(or you can use class, do as you see fit)

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-all-setups.tsx
> +            const versions = Object.entries(componentsVersions).map(([componentId = '', tag = '']) => ({componentId, tag} as RawVersion));
Using default values `componentId = '', tag = ''` seems wrong.
Why would we want to get either of `"": 'x.y.z'`, `"myComponent": ''`, or `"":''` ?

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-all-setups.tsx
> +            const response = await fetch("https://api.github.com/repos/Drill4J/e2e/dispatches", {
1. Wrap calls to e2e repo in its own module.
    ```
      import e2e from 'e2e';
      ...
      await e2e.runAllSetups(versions)
    ```
    **WHY**: less fluff - juggling with headers and handling response must not be a form's concern.
2. In case Axios is already installed, use it, please. If not - ok, leave fetch as it is

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +                const ids = setups.find(({id}) =>  setupId === id)?.componentIds || [];
There is already `ledger.getSetupById`. Just make it public

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +                const latestVersion = props.ledger.getComponentsLatestVersions(ids);
`latestVersion_s_` (why singular?)

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setups-for-component.tsx
> +            const versions = Object.entries(componentsVersions).map(([componentId = '', tag = '']) => ({componentId, tag} as RawVersion));
code duplication

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setups-for-component.tsx
> +                form.setFieldValue("componentsVersions",latestVersion.reduce((acc, {componentId, tag}) => ({...acc, [componentId]: tag}), {}))
code duplication №2

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +          }catch (e) {
Check that Prettier & linter are working, pls

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +        const res = await fetch("https://raw.githubusercontent.com/Drill4J/e2e/main/setups.json")
- Move to e2e module
- Stop placing raw API requests in component implementations

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +            const response = await fetch("https://api.github.com/repos/Drill4J/e2e/dispatches", {
Move to e2e module

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +  const params = autotestsSetups[values.setupId].params.reduce((acc: Record<string, string[]>, params) => {
Requires long reading to understand. Refactor to a separate function, please.

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +    {/*TODO map params*/}
"ADD TODO" is not a feature, please use commit prefixes mindfuly

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +          const response = await fetch("https://api.github.com/repos/Drill4J/e2e/dispatches", {
move to e2e module

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +            <VersionsSelect componentIds={setups.find(({id}) =>  values.setupId === id)?.componentIds || []} ledger={props.ledger} fieldNamePrefix={'componentsVersions'}/>
Extract `setups.find(({id}) =>  values.setupId === id)?.componentIds || []` to render function body

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setups-for-component.tsx
> +          const response = await fetch("https://api.github.com/repos/Drill4J/e2e/dispatches", {
move to e2e module

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ledger/src/index.ts
> +    const response = await fetch("https://api.github.com/repos/Drill4J/e2e/dispatches", {
Move to e2e module.
BTW you even have the comment above! A great hint that this code should live elsewhere.

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setups-for-component.tsx
> +                const filteredSetups = setups.filter(({ componentIds }) => componentIds.includes(componentId));
Change const name for clarity. "filtered" does not say much - `.filter` is already here, you better say what is the output of that process.

2022-01-17 09:46 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setups-for-component.tsx
> +                const setupsComponents = Array.from(new Set(
Avoid lengthy chains of `entries(), values(), map(), reduce()`
This is very hard to read, and if its more than 2 lines long, you probably should explain yourself more clearly 😃

2022-01-17 10:57 UTC, IliaSolovev commented on packages/ui/src/components/forms/start-all-setups.tsx
> +            const response = await fetch("https://api.github.com/repos/Drill4J/e2e/dispatches", {
Axios is not installed

2022-01-18 06:40 UTC, IliaSolovev commented on packages/ui/src/components/forms/start-setup.tsx
> +  const params = autotestsSetups[values.setupId].params.reduce((acc: Record<string, string[]>, params) => {
I don't know how to refactor ше иуееук.
I have created a function groupParamsByName. But I think it's still hard to read

2022-01-18 08:17 UTC, RomanDavlyatshin requested changes

2022-01-19 12:06 UTC, RomanDavlyatshin commented on packages/ui/src/components/forms/start-setup.tsx
> +          as={'textarea'}
@IliaSolovev FYI - this is clearly not a "refactor" since you're changing the _feature's implementation_
It's either `fix` or `feat` (lookup the angular's commit conventions, for example https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
(no need to edit the commit message, just keep it in mind in the future)

2022-01-19 12:10 UTC, RomanDavlyatshin approved these changes
Looks good to me 👍 You can merge it now
P.S. Just check the comment https://github.com/Drill4J/vee-table/pull/1#pullrequestreview-856701651

2022-01-20 07:46 UTC, merged